taps:
  - homebrew/cask
  - homebrew/cask-versions
  - homebrew/cask-fonts
  - homebrew/core

packages:
  - { name: zsh, state: present }
  - { name: git, state: present }
  - { name: wget, state: present }
  - { name: vim, state: present }
  - { name: tree, state: present }
  - { name: nodebrew, state: present }
  - { name: jq, state: present }
  - { name: docker, state: present }
  - { name: awscli, state: present }
  - { name: ansible, state: present }
  - { name: python, state: present }
  - { name: python3, state: present }
  - { name: tmux, state: present }